services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=restaurantapp'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=secret'
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/restaurantapp'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
volumes:
  db_data:
