spring.application.name=tech-challenge-fase-01

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

# spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always

spring.sql.init.schema-locations=classpath:db/postgres/schema.sql
#spring.sql.init.data-locations=classpath:db/postgres/data.sql

security.jwt.secret=e88672e7-8453-4299-8038-57c4f90cca98
security.jwt.expiration-ms=86400000
